# Generated by Django 2.1.1 on 2018-10-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
